os: linux
dist: bionic

language: python
python:
  - 3.6

branches:
  only:
    - master

matrix:
  include:
  - name: Basic Tests
    before_install:
      - python3 -m pip install -U pip wheel setuptools pytest pytest-cov
    install:
      - pushd ./alephzero/ && sudo make install -j && popd
      - python3 -m pip install -r requirements.txt
      - CFLAGS="-O0 -fprofile-arcs -ftest-coverage --coverage" python3 setup.py install
    script:
      - python3 -m pytest --cov=a0 tests/
      - gcov -o build/temp.linux-x86_64-3.6/ module.cc
    after_success:
      - bash <(curl -s https://codecov.io/bash)
  - name: Lint
    install:
      - python -m pip install -U flake8 yapf
    script:
      - python -m yapf -d -r .
      - python -m flake8
