os: linux
dist: bionic

language: python
python:
  - 3.6

matrix:
  include:
  - name: Basic Tests
    before_install:
      - python3 -m pip install -U pip wheel setuptools pytest
    install:
      - pushd ./alephzero/ && sudo make install -j && popd
      - python3 -m pip install -r requirements.txt
      - python3 setup.py install
    script:
      python3 -m pytest tests/
