os: linux
dist: bionic

language: python
python:
  - 3.6

matrix:
  include:
  - name: Basic Tests
    before_install:
      - python3 -m pip install --upgrade pip wheel setuptools pytest
    install:
      - python3 -m pip install -r requirements.txt
      - python3 setup.py install
    script:
      python3 -m pytest tests/
