name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  bionic:
    name: Ubuntu Bionic

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:18.04'

    steps:
    - uses: actions/checkout@v2
    - name: install apt deps
      run: apt update && apt install --no-install-recommends -y curl g++ make pkg-config python3-dev python3-pip
    - name: install pip deps
      run: python3 -m pip install -U pip wheel setuptools pytest pytest-cov
    - name: install pip requirements
      run: python3 -m pip install -r requirements.txt
    - name: install alephzero core
      run: cd ./alephzero/ && make install -j && cd ..
    - name: install alephzero python
      run: CFLAGS="-O0 -fprofile-arcs -ftest-coverage --coverage" python3 setup.py install
    - name: run tests
      run: python3 -m pytest --cov=a0 tests/
    - name: generate coverage
      run: gcov -o build/temp.linux-x86_64-3.6/ module.cc
    - name: upload coverage
      run: bash <(curl -s https://codecov.io/bash)


  lint:
    name: Lint

    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:20.04'

    steps:
    - uses: actions/checkout@v2
    - name: install apt deps
      run: apt update && apt install --no-install-recommends -y python3-pip
    - name: install pip deps
      run: python3 -m pip install -U flake8 yapf
    - name: yapf
      run: python3 -m yapf -d -r -e alephzero .
    - name: flake8
      run: python3 -m flake8
